# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
      # uses: snok/install-poetry@93ada01c735cc8a383ce0ce2ae205a21c415379b
      uses: snok/install-poetry@v1.3.4
    - name: Install poetry dependencies
      run: |
        cd example-app
        poetry install --no-root

  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-concurrency
      cancel-in-progress: false
    steps:
    - name: Run lint
      run: poetry run task lint
  
  formatter:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-concurrency
      cancel-in-progress: false
    steps:
    - name: Run formatter
      run: poetry run task formatter

  security:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-concurrency
      cancel-in-progress: false
    steps:
    - name: Run security
      run: poetry run task security

  unittesting:
    runs-on: ubuntu-latest
    steps:
    - name: Run unit tests
      run: poetry run task test
        
